### ISSUE TITLE
TODO: Saving and loading of Todo list(s)

### ISSUE THREAD

**Issue by DuskyElf** [DuskyElf/todo-rs#2]
All the todos with it's data be stored in some file, and then loaded automatically next time.

**Comment by cndofx** [comment]
Where do you think the file should be stored? I think the "proper" location would be `$XDG_DATA_HOME` / `$HOME/.local/share` on linux and somewhere under `%AppData%` on windows, but a simple file in the same directory as the binary could also work depending on how the program is meant to be used. I might work on something when I have time if you're accepting PRs for this

**Comment by DuskyElf** [comment]
Sorry for a late reply, though I'm up again with these projects!

yeah, I think the file should be stored in the `~/local/share` for linux, and `%AppData%` on windows. But I don't really know about windows, also I haven't tested this project on windows anyways.

I don't want it to be complicated, just a neat little function to dump the `core_state: CoreState` structure in a file, (could use Tokio Serialization maybe), and also to parse it next time.

PRs are always open, I would like if you contribute <3

**Comment by DuskyElf** [comment]
@cndofx Could contact me on Discord - DuskyElf#7999
